name: "Build workflow"
on:
  pull_request:
  push:
    tags:
      - v**
    branches:
      - main

env:
  SANDBOX_CONFIG: dev
  SANDBOX_GENESIS: genesis/dev/genesis.json

jobs:
  build-test:
    runs-on: ubuntu-20.04
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - run: python3 --version
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pip, lint, and units
        run: make build-and-test
  run-integration-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python }}"
      - name: Test Python version
        run: |
          installed="$(python --version)"
          expected="${{ matrix.python }}"
          echo $installed
          [[ $installed =~ "Python ${expected}" ]] && echo "Configured Python" || (echo "Failed to configure Python" && exit 1)
      - name: Start algod
        run: make algod-start
      - name: Setup integration test environment
        run: make pip-development unit-test
      - name: Setup Jupyter notebooks environment
        run: make pip-notebooks
      - name: Run integration tests and Jupyter notebooks tests
        run: make gh-blackbox
      - name: Stop algod
        run: make algod-stop
